<?php
namespace Aura\Uri\Url;

/**
 * Test class for Factory.
 * Generated by PHPUnit on 2012-07-21 at 17:13:55.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new Factory($GLOBALS['_SERVER']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers Aura\Uri\Url\Factory::newInstance
     * @todo Implement testNewInstance().
     */
    public function testNewInstance()
    {
        $spec = 'http://anonymous:guest@example.com/path/to/index.php/foo/bar.xml?baz=dib#anchor';
        $url  = $this->object->newInstance($spec);
        $this->assertTrue($url instanceof \Aura\Uri\Url);
    }

    /**
     * @covers Aura\Uri\Url\Factory::newCurrent
     * @todo Implement testNewCurrent().
     */
    public function testNewCurrent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
