<?php
namespace Aura\Uri\Url;

/**
 * Test class for Factory.
 * Generated by PHPUnit on 2012-07-21 at 17:13:55.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $factory;

    /**
     * @covers Aura\Uri\Url\Factory::newInstance
     * @todo Implement testNewInstance().
     */
    public function testNewInstance()
    {
        $this->factory = new Factory([]);
        $spec = 'http://anonymous:guest@example.com/path/to/index.php/foo/bar.xml?baz=dib#anchor';
        $url  = $this->factory->newInstance($spec);
        $this->assertTrue($url instanceof \Aura\Uri\Url);
    }

    /**
     * @covers Aura\Uri\Url\Factory::newCurrent
     * @todo Implement testNewCurrent().
     */
    public function testNewCurrent()
    {
        $this->factory = new Factory([
            'HTTP_HOST'   => 'example.com',
            'REQUEST_URI' => '/path/to/index.php/foo/bar.xml?baz=dib',
        ]);
        
        $url = $this->factory->newCurrent();
        $actual = $url->__toString();
        $expect = 'http://example.com/path/to/index.php/foo/bar.xml?baz=dib';
        $this->assertSame($expect, $actual);
    }
    
    public function testNewCurrent_https()
    {
        $this->factory = new Factory([
            'HTTPS'       => 'on',
            'HTTP_HOST'   => 'example.com',
            'REQUEST_URI' => '/path/to/index.php/foo/bar.xml?baz=dib',
        ]);
        
        $url = $this->factory->newCurrent();
        $actual = $url->__toString();
        $expect = 'https://example.com/path/to/index.php/foo/bar.xml?baz=dib';
        $this->assertSame($expect, $actual);
    }
    
    public function testNewCurrent_ssl()
    {
        $this->factory = new Factory([
            'SERVER_PORT' => '443',
            'HTTP_HOST'   => 'example.com',
            'REQUEST_URI' => '/path/to/index.php/foo/bar.xml?baz=dib',
        ]);
        
        $url = $this->factory->newCurrent();
        $actual = $url->__toString();
        $expect = 'https://example.com/path/to/index.php/foo/bar.xml?baz=dib';
        $this->assertSame($expect, $actual);
    }
    
    public function testNewCurrent_noHttpHost()
    {
        $this->factory = new Factory([
            'REQUEST_URI' => '/path/to/index.php/foo/bar.xml?baz=dib',
        ]);
        
        $url = $this->factory->newCurrent();
        $actual = $url->__toString();
        $expect = '';
        $this->assertSame($expect, $actual);
    }
    
    public function testNewCurrent_noRequestUri()
    {
        $this->factory = new Factory([
            'HTTP_HOST'   => 'example.com',
        ]);
        
        $url = $this->factory->newCurrent();
        $actual = $url->__toString();
        $expect = 'http://example.com';
        $this->assertSame($expect, $actual);
    }
    
    public function testIssue9()
    {
        $factory = new Factory([
            'HTTP_HOST'   => 'example.com',
        ]);
        $string = 'http://localhost:8000/site/foo/bar';
        $url = $factory->newInstance($string);
        $this->assertSame(array('site', 'foo', 'bar'), $url->path->getArrayCopy());
    }
}
